global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: eu1
    replica: 0

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus0_eu1:9090']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['sidecar0_eu1:19090']