version: "3"  
services:  
  prometheus:
    image: prom/prometheus:latest
    ports:
     - 9090:9090
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
     - "./prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml"

  metric-generator:
    image: metric-generator
    ports:
      - 8080:8080