global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    cluster: eu1
    replica: 0

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'store'
    static_configs:
      - targets: ['store:19090']
  - job_name: 'query'
    static_configs:
      - targets: ['querier:29090']